config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :categories do
    get :sub_category, on: :collection
  end

  resources :articles do
    get :all_articles, on: :collection
    post :add_comment, on: :member
    delete :delete_comment, on: :member
    post :reply, on: :member
  end

  root "articles#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :sub_categories
  belongs_to :user
  has_many :comments, as: :commentable
  accepts_nested_attributes_for :comments
  validates :title, presence: true, length: {maximum: 512}
  validates :content, presence: true, length: {maximum: 2048}

  def self.article_search(search, page)
    Article.where('title LIKE ? ', search).paginate(page: page, per_page: 3)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :add_comment, :reply]

  def add_comment
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to articles_path
    else
      puts "else"
      flash[:alert] = "Error adding reply."
      redirect_to articles_path
    end 
  end

  def all_articles
    @articles = Article.all  
  end

  def create
    @article = Article.new(article_params)
    @sub_categories = SubCategory.all
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
    @sub_categories = SubCategory.all
  end

  def index
    search = params[:search]
    if search.present?
      @articles = Article.article_search(search, params[:page])
    else
      @articles = Article.paginate(page: params[:page], per_page: 3)
      # @articles = Article.all
    end
  end

  def new
    @article = Article.new
    @sub_categories = SubCategory.all
  end

  def reply
    @comment = @article.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:notice] = "Successfully created ReplyComment."
      redirect_to articles_path
    else
      puts "else"
      flash[:alert] = "Error adding comment."
      redirect_to articles_path
    end 
  end

  def show
    @comments = Comment.where(article_id: @article.id)
  end

  def update
    if (current_user.admin) || (@article.user_id == current_user.id)
      @sub_categories = SubCategory.all

      respond_to do |format|
        if @article.update(article_params)
          format.html { redirect_to @article, notice: 'Article was successfully updated.' }
          format.json { render :show, status: :ok, location: @article }
        else
          format.html { render :edit }
          format.json { render json: @article.errors, status: :unprocessable_entity }
        end
     end
    else
      redirect_to @article, notice: 'Not admin or creator.'
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, sub_category_ids: [], comment_attributes: [:comment, :user_id, :article_id, :commentable_id, :commentable_type])
    end

    def comment_params
      params.require(:comment).permit(:comment, :user_id, :article_id, :commentable_id, :commentable_type, :parent_id) 
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="row">
    <div class="col-2"></div>
    <div class="col-6">
      <div class="form-inputs">
        <%= f.input :title, size: 30 %>
        <%= f.input :content, :input_html => { id: "wysiwyg"}%>
        <br>
        <div class="container">
          <div class="row">
            <% @sub_categories.all.each do |sub_category| %>
              <div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">
                <li><%= check_box_tag "article[sub_category_ids][]", sub_category.id, @article.sub_category_ids.include?(sub_category.id)%>
                <%= sub_category.name %></li>
              </div>
              <br>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <br>
  <div class="form-actions d-flex justify-content-center"> 
    <%= f.button :submit , class: "btn btn-success col-md-4 pull-left" %>
  </div>
<% end %>

<script>
  $('#wysiwyg').froalaEditor({
    inlineMode: false,
    heightMin: '200px',
    widthMin: '500px',
    toolbarButtons: ['fullscreen','bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'color', 'clearFormatting', '|', 'emoticons', 'fontAwesome', 'specialCharacters', '-', 'paragraphFormat', 'lineHeight', 'paragraphStyle', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', '|', 'insertLink', 'insertImage', 'insertVideo', 'insertFile', 'insertTable', '-', 'insertHR', 'selectAll', 'print', 'help','|', 'undo'],
  });

  $("input").focus(function(){
        $(this).css("background-color", "#cccccc");
    });
  $("input").blur(function(){
        $(this).css("background-color", "#ffffff");
    });

</script>

app/views/articles/all_articles.html.erb
<h1>Listing Articles</h1>

<table>
  <div class="container">
    <div class="col">
      <div class="col-md-4 offset-md-4">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Content</th>
              <th>Created_by</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @articles.each do |article| %>
              <tr>
                <td><%= article.title %></td>
                <div class= "fr-view">
                  <td><%= article.content %></td>
                </div>
                <td><%= article.user.email %></td>
                <td>
                  <div class="btn-stack">
                    <%= link_to 'Show', article, class: "btn btn-sm btn-success" %>
                    <%= link_to 'Edit', edit_article_path(article), class: "btn btn-sm btn-secondary" %>
                    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger"  %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</table>

<br>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<br/><br />

<div class="mb-4 mt-2">
  <%= link_to 'Show', @article, class: "btn btn-sm btn-info" %> |
  <%= link_to 'Back', articles_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/articles/index.html.erb
<h1> Articles</h1>
<div class="container d-flex justify-content-end">
  <%= link_to 'New Article', new_article_path, class: "btn btn-primary"%>
</div>

<div class="d-flex align-items-center flex-column justify-content-center h-100" id="header" style="margin-left: 75px; margin-right: 75px; margin-top: 20px;">
  <ul class="pagination justify-content-center">
    <div class="page-item">
      <% @articles.each do |article| %>
        <div class="row" style="height: 80px">
          <div class="col-6 col-md-4">
            Date: <%= article.created_at.strftime('%A, %B %d') %>
          </div>
          <div class="col-6 col-md-4">
            <b><h2><%= article.title %></h2></b>
          </div>
          <div class="col-6 col-md-4 text-right">
            <span class="float-right">
              <%= link_to 'Edit', edit_article_path(article), class: "btn btn-sm btn-primary" %>
            </span> 
          </div>
        </div>

        <div class="row">
          <div class="col align-self-center">
            <div class= "fr-view">
              <%= article.content.html_safe %>
            </div>
          </div>
        </div>

        <div class="row ">
        <div class="col-2 col-md-2"></div>
        <div class="col-8 col-md-6 mx-auto mb-4 mt-2">
          <div style="background-color: antiquewhite;">
            <% article.comments.each do |com| %>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-2">
                    <%= image_tag(com.user.user_image.url(:thumb), class: "rounded-circle" , height: '54') if com.user.user_image?%>
                  </div>
                  <div class="col-sm-8">
                    <p><%= com.comment %></p>
                  </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-4"></div>
                    <div class="col-sm-8">   
                      <p><%= com.user.email %></p>
                    </div>
                    <div class="col-sm-4"></div>
                    <div class="col-sm-8">
                      <p><%= localize(com.created_at, format: :long) %></p>
                    </div>
                  </div>
                   
                  <div class="row justify-content-center align-items-center" class="col-md-6">
                    <div class="col-sm-4">
                      <%= simple_nested_form_for(:comment, :url => reply_article_url(article.id), method: :post, :html=>{:multipart => true}) do |c| %>
                        <%= c.hidden_field :user_id, value: current_user.id %>
                        <%= c.hidden_field :parent_id, value: article.id %>
                        <a href="#" class="<%= com.id %>" id="show_reply">Reply</a>
                        <div id="reply_<%= com.id %>" class="hidden">
                          <%= c.input :comment, as: :text, input_html: {rows: 5} , placeholder: "comment " %>
                          <%= c.submit "Reply", class: "btn btn-primary" %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                  <hr>
                </div>
              <% end %>
            </div>
          </div>   
        </div>
          
        <div class="row justify-content-center align-items-center" class="col-md-4">
          <div class="col-4 sm-8">
            <div class="form-group">
              <%= simple_nested_form_for(:comment, :url => add_comment_article_url(article.id), method: :post, :html=>{:multipart => true}) do |c| %>
                <%= c.hidden_field :user_id, value: current_user.id %>
                <%= c.hidden_field :commentable_type, value: "Article" %>
                <%= c.hidden_field :commentable_id, value: article.id %>
                <%= c.hidden_field :parent_id, value: article.id %>
                <%= c.input :comment, as: :text, input_html: {rows: 5} , placeholder: "Add Comment " %>
                <%= c.submit "Post Comment", class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
        <hr>
      <% end %>
    </div>
  </ul>
    <%= will_paginate @articles, :container => false %>
</div>

<script type="text/javascript">
  $(function() {
  $('a#show_reply').click(function(event){
    event.preventDefault();
    var comm_id = $(this).attr('class');
    $('div#reply_'+comm_id).toggle();
    });
  });      
</script>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<br /><br />

<div class="mb-4 mt-2">
  <%= link_to 'Show', @article, class: "btn btn-sm btn-info" %> |
  <%= link_to 'Back', articles_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <div class="card-columns">
    <div class="mr-10 p-1 mt-sm-1 mb-sm-1 mx-auto ">
      <div class="col-sm-2"></div>
      <div class="card bg-light w-150">
        <h4 class="Article Details"><center>Article Details</center></h4>
        <div class="card-body text-center">
          <p class="card-text">
            <p><h2><%= @article.title%></h2></p>
          </p>
        </div>
              
        <div class="card-body text-center">
          <p class="card-text">
            <div class= "fr-view">
              <%= @article.content.html_safe %>
            </div>
          </p>
        </div>

        <div class="card-body text-center">
          <p class="card-text">
            <p><strong>Sub Categories:</strong></p>
            <ul>
              <% @article.sub_categories.each do |sub_category| %>
                <li><%= sub_category.name %></li>
              <% end %>
            </ul>
          </p>
        </div>      
      </div>
    </div>
  </div>
</div>
   
<div class="mb-4 mt-2 d-flex justify-content-center">   
  <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-sm btn-info" %> |
  <%= link_to 'Back', articles_path, class: "btn btn-sm btn-secondary" %>
</div>