config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :categories do
    get :sub_category, on: :collection
  end

  resources :articles do
    get :all_articles, on: :collection
    post :add_comment, on: :member
    delete :delete_comment, on: :member
    post :reply, on: :member
  end

  root "articles#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
  has_many :sub_categories, dependent: :destroy
  has_many :articles, through: :sub_categories
  accepts_nested_attributes_for :sub_categories, reject_if: proc { |attributes| attributes['name'].blank? }, allow_destroy: true
  validates :name, :presence => true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def create
    @category = Category.new(category_params)
  
    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def edit
  end

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
    @category.sub_categories.build
  end
  
  def show
    @category = Category.find(params[:id]) 
  end

  def sub_category
    @category = Category.all
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, sub_categories_attributes: [:id, :name])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= simple_nested_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="row">
    <div class="col-2"></div>
    <div class="col-6">
      <div class="form-inputs">
        <%= f.input :name %>
      </div>

      <h2>Sub categories</h2>
      <%= f.simple_fields_for :sub_categories do |sub_category | %>
        <div class="sub_category_field">
          <div class="form-inputs">
            <%= sub_category.input :name %>
          </div>
          <div class="text-right">
            <%= sub_category.link_to_remove "X", class: "btn btn-sm btn-danger" %>
          </div>
        </div>
      <% end %>
      <div id="sub_categories"></div>
    </div>
    
    <div class="col-6"></div>
    <p><%= f.link_to_add "+ Add SubCategory", :sub_categories, :data => { :target => "#sub_categories" }, class: "btn btn-block btn-primary pull-left" %></p> 
    <div class="col-8"></div>
    <div class="float-right">
      <%= f.button :submit, class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<div class="mb-4 mt-2">
  <%= link_to 'Show', @category, class: "btn btn-sm btn-info" %> |
  <%= link_to 'Back', categories_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/categories/index.html.erb
<h1>Listing Categories</h1>
<table>
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @categories.each do |category| %>
              <tr>
                <td><%= category.name %></td>
                <td>
                  <div class="btn-stack">
                    <%= link_to 'Show', category, class: "btn btn-success" %>
                    <%= link_to 'Edit', edit_category_path(category), class: "btn btn-secondary" %>
                    <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</table>

<br>
<div class="mb-4 mt-2">
  <%= link_to 'New Category', new_category_path, class: "btn btn-sm btn-primary" %> |
  <%= link_to 'Back', articles_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/categories/new.html.erb
<h2>New Category</h2>

<%= render 'form' %>

<div class="mb-4 mt-2">
  <%= link_to 'Back', categories_path, class: "btn btn-sm btn-secondary" %>
</div>

app/views/categories/show.html.erb
<div class="container">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
       <th colspan="2"><center>Category Details</center></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @category.name %></td>
      </tr>

      <tr> 
        <td><strong>Sub Categories</strong></td>
        <% if @category.sub_categories.any? %>
        <td>
          <ul>
            <% @category.sub_categories.each do |sub_category| %>
              <li><%= sub_category.name %></li>
            <% end %>
          </ul>
          <% else %>
            <p> none available </p>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<div class="mb-4 mt-2">
  <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-sm btn-info" %> |
  <%= link_to 'Back', categories_path, class: "btn btn-sm btn-secondary" %>   
</div>

app/views/categories/sub_category.html.erb
<center><h3>Sub Categories</h3></center>
<br></br>
<div class="container">
  <% @category.each do |f| %>
    <% f.sub_categories.each do |sub| %>
      <p><%= sub.name %></p>
    <% end%>
  <% end %>
</div>