config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :categories do
    get :sub_category, on: :collection
  end

  resources :articles do
    get :all_articles, on: :collection
    post :add_comment, on: :member
    delete :delete_comment, on: :member
    post :reply, on: :member
  end

  root "articles#index"

end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <footer class="page-footer" >
    <div class="container text-center">
      <copyright>
        &copy; Copyright <%= Time.now.year %> BlogApp
      </copyright>
    </div>
  </footer>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#"> Blog Application </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item active">
        <a class="nav-link" href="/articles">Home <span class="sr-only">(current)</span></a>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"aria-haspopup="true" aria-expanded="false"> More</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="/categories">Categories</a>
            <%= link_to 'Sub Categories', sub_category_categories_path, class: "dropdown-item" %>
            <%= link_to 'All Articles', all_articles_articles_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>

      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>
          <% end %>
        </ul>
      </div>
         
      <%if user_signed_in? %>
        <div class="st-search" style="padding-left: 270px;">
          <form class="st-search-form" action="<%= articles_path %>">
            <div class="input-group">
              <span class="input-group-btn">
                <div class="btn st-ds-close"></div>
              </span>
              <input id="main_search" name="search" value="<%= params[:search] %>" type="text" class="article_search form-control input-search" placeholder="Search by Article title ">
              <span class="input-group-btn">
                <button class="btn st-search-go" type="submit"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
        </div>
      <% end %> 
        
      <% if user_signed_in? %>
        <li class="nav-item dropdown" >
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"aria-haspopup="true" aria-expanded="false"> Hello Admin</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'My Account', edit_user_registration_path, :class => "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class =>"dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item navbar-right">
          <div style="padding-left: 800px;">
            <span class="glyphicon glyphicon-user"></span><%= link_to 'Login', new_user_session_path, class: "btn btn-primary" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>